export type PriceRow = { name: string; detail?: string; price: string };
export type Item = { title: string; text: string };

export type Service = {
  slug: string;
  shortName: string;
  kicker: string;
  title: string;
  subtitle: string;
  description: string;
  heroImage: string;
  heroAlt: string;
  highlights: Item[];
  includeTitle: string;
  includeIntro?: string;
  includes: Item[];
  whyTitle: string;
  whyIntro?: string;
  benefits: Item[];
  stepsTitle: string;
  stepsIntro?: string;
  steps: Item[];
  extraTitle: string;
  extraItems: Item[];
  pricingNote?: string;
  pricing: PriceRow[];
};

export const services: Service[] = [
  {
    slug: "fast-fixed",
    shortName: "Fast & Fixed",
    kicker: "Implanturi dentare · Fast & Fixed",
    title: "Dinți ficși în 24h",
    subtitle: "Fast & Fixed. Zâmbet complet, rapid.",
    description:
      "Soluție modernă de reabilitare orală completă — tratament rapid, sigur și minim invaziv, cu recuperare asistată medical.",
    heroImage: "/heroes/fast-fixed.jpg",
    heroAlt: "Lucrare Fast & Fixed pe implante",
    highlights: [
      { title: "Dinți ficși în 24h", text: "Zâmbet complet, imediat." },
      { title: "Siguranță și predictibilitate", text: "Plan de tratament personalizat." },
      { title: "Estetică și funcționalitate", text: "Fără proteze mobile, confort maxim." },
    ],
    includeTitle: "Ce este protocolul Fast & Fixed?",
    includeIntro:
      "Tehnică avansată ce folosește un număr redus de implante (de regulă 4 la mandibulă și 6 la maxilar) pentru fixarea unei lucrări provizorii în ~24 de ore.",
    includes: [
      { title: "Indicat pacienților", text: "Fără dinți sau cu dinți irecuperabili." },
      { title: "Poziționare strategică", text: "Reduce nevoia de adaosuri osoase." },
      { title: "Lucrare provizorie fixă", text: "Înșurubată, nu se scoate noaptea." },
    ],
    whyTitle: "De ce clinica noastră?",
    whyIntro: "Planificare digitală, chirurgie minim invazivă și laborator propriu.",
    benefits: [
      { title: "Dinți ficși în 24h", text: "Confort imediat." },
      { title: "Timp total redus", text: "Mai puține ședințe." },
      { title: "Estetică și stabilitate", text: "Fără proteze mobile." },
      { title: "De multe ori fără grefe osoase", text: "Evităm proceduri suplimentare." },
      { title: "Cost optimizat", text: "Investiție inteligentă." },
      { title: "Mentenanță clară", text: "Follow-up pe termen lung." },
    ],
    stepsTitle: "Etapele tratamentului",
    stepsIntro: "Un proces clar, în 5 pași.",
    steps: [
      { title: "Consultație & diagnostic", text: "Analizăm situația și stabilim opțiunile." },
      { title: "Plan de tratament", text: "Planificare digitală personalizată." },
      { title: "Chirurgie implaturi", text: "4 la mandibulă, 6 la maxilar." },
      { title: "Lucrare provizorie", text: "În ~24 de ore." },
      { title: "Lucrare definitivă", text: "3–6 luni." },
    ],
    extraTitle: "Ce mai trebuie să știi?",
    extraItems: [
      { title: "Candidați", text: "Persoane fără dinți sau cu dinți irecuperabili, cu o stare generală de sănătate bună." },
      { title: "Igienă", text: "Îngrijire riguroasă și controale periodice." },
      { title: "Garanții", text: "Materiale premium și garanție pentru lucrări." },
    ],
    pricing: [
      { name: "Implanturi + lucrare provizorie (~24h)", detail: "Consultație, imagistică, chirurgie, lucrare provizorie înșurubată", price: "1–2 zile" },
      { name: "Lucrare definitivă (3–6 luni)", detail: "Structură și dinți definitivi, zirconiu / ceramică, garanție", price: "3–6 luni" },
    ],
  },
  {
    slug: "stomatologie-generala",
    shortName: "Generală",
    kicker: "Zâmbet sănătos · viață mai bună",
    title: "Stomatologie Generală",
    subtitle: "Îngrijire completă pentru zâmbetul tău, fără compromisuri.",
    description:
      "De la consultație periodică și igienizare profesională, la tratamente minim invazive pentru carii, afecțiuni gingivale și urgențe. Punem accent pe prevenție, confort și rezultate estetice naturale.",
    heroImage: "/heroes/stomatologie-generala.jpg",
    heroAlt: "Cabinet de stomatologie generală",
    highlights: [
      { title: "Tehnologie modernă", text: "Diagnostic precis și tratamente sigure." },
      { title: "Echipă noastră", text: "Profesioniști cu experiență și empatie." },
      { title: "Zâmbete reale", text: "Rezultate naturale pe termen lung." },
    ],
    includeTitle: "Ce include stomatologia generală?",
    includeIntro: "Toate serviciile esențiale pentru sănătatea și frumusețea zâmbetului tău, într-un singur loc.",
    includes: [
      { title: "Consultație & diagnostic", text: "Examinare clinică, imagistică digitală și plan personalizat." },
      { title: "Igienizare profesională", text: "Detartraj, ultrasunete, airflow, periaj și instrucțiuni de igienă." },
      { title: "Tratamentul cariei", text: "Obturații estetice din compozit, tehnici aditive moderne." },
      { title: "Tratament endodontic", text: "Tratamente de canal moderne pentru salvarea dinților afectați." },
      { title: "Parodontologie de bază", text: "Managementul gingivitei și mentenanță parodontală." },
      { title: "Urgențe stomatologice", text: "Calmarea durerii și intervenții rapide." },
    ],
    whyTitle: "De ce să alegi abordarea noastră?",
    whyIntro: "Pentru că fiecărui pacient contează, iar noi punem grijă și profesionalism pe primul loc.",
    benefits: [
      { title: "Abordare empatică și relaxantă", text: "Fără frica de dentist." },
      { title: "Tehnologie digitală", text: "Diagnostic precis și tratamente mai eficiente." },
      { title: "Tratamente minim invazive", text: "Cât mai puțină intervenție." },
      { title: "Programări eficiente", text: "Timpul tău contează." },
      { title: "Transparență totală a costurilor", text: "Fără surprize, tot din timp." },
      { title: "Prevenție activă", text: "Zâmbet sănătos, an de an." },
    ],
    stepsTitle: "Cum decurge o vizită?",
    stepsIntro: "Un proces simplu, clar și sigur, pentru confortul tău.",
    steps: [
      { title: "Anamneză & evaluare", text: "Discuție despre istoricul medical și examinarea clinică." },
      { title: "Investigații & diagnostic", text: "Radiografii sau imagistică suplimentară la nevoie." },
      { title: "Plan & opțiuni", text: "Diagnostic precis, priorități și costuri." },
      { title: "Tratament & prevenție", text: "Intervenții sigure, fără durere, cu anestezie locală." },
    ],
    extraTitle: "Recomandări de prevenție",
    extraItems: [
      { title: "Control la 6 luni", text: "Depistăm din timp orice problemă." },
      { title: "Periaj corect", text: "De 2 ori/zi, de două ori pe zi." },
      { title: "Gutiere de protecție", text: "Pentru sport, bruxism sau ocluzie dificilă." },
    ],
    pricing: [
      { name: "Consultație inițială", detail: "Anamneză, evaluare clinică, recomandări", price: "150–250 lei" },
      { name: "Igienizare profesională", detail: "Detartraj + airflow/periaj, instrucțiuni", price: "250–400 lei" },
      { name: "Obturație compozit", detail: "Închidere, izolare, estetică, restaurare cavități", price: "300–600 lei" },
      { name: "Tratament endodontic", detail: "Instrumentare, dezinfecție și obturație canal", price: "600–1.200 lei" },
      { name: "Parodontologie de bază", detail: "Scaling în țesuturi moi, mentenanță", price: "400–800 lei" },
    ],
  },
  {
    slug: "implantologie",
    shortName: "Implanturi",
    kicker: "Implanturi dentare · tehnologie · încredere",
    title: "Implantologie Dentară Avansată",
    subtitle: "Soluția modernă și definitivă pentru înlocuirea dinților lipsă.",
    description:
      "Redă funcționalitatea masticatiei și estetica naturală a zâmbetului tău cu ajutorul implanturilor dentare de înaltă calitate, inserate prin tehnici chirurgicale minim invazive și planificare digitală 3D.",
    heroImage: "/heroes/implantologie.jpg",
    heroAlt: "Implant dentar și coroană",
    highlights: [
      { title: "Planificare 3D", text: "Precizie maximă." },
      { title: "Materiale premium", text: "Titan / zirconiu." },
      { title: "Rezultate naturale", text: "Zâmbet de durată." },
    ],
    includeTitle: "Ce este implantul dentar?",
    includes: [
      { title: "Ce reprezintă?", text: "O rădăcină artificială din titan sau zirconiu care se integrează perfect în osul maxilar." },
      { title: "Durabilitate pe termen lung", text: "O alternativă superioară punților clasice sau protezelor mobile." },
      { title: "Soluții personalizate", text: "De la înlocuirea unui singur dinte până la reabilitări orale totale." },
    ],
    whyTitle: "De ce să alegi abordarea noastră?",
    benefits: [
      { title: "Rată de succes extrem de ridicată", text: "Prin ghidaj digital 3D." },
      { title: "Chirurgie minim invazivă", text: "Confortabilă și fără durere (anestezie/sedare)." },
      { title: "Estetică impecabilă", text: "Imposibil de diferențiat de un dinte natural." },
      { title: "Prevenirea resorbției osoase", text: "Și a atrofiei maxilare." },
      { title: "Garanție extinsă", text: "Și materiale premium de la producători de top." },
      { title: "Planuri de finanțare flexibile", text: "Și transparență a costurilor." },
    ],
    stepsTitle: "Etapele tratamentului",
    steps: [
      { title: "Consultație & imagistică 3D", text: "Evaluarea stării de sănătate și tomografie CBCT." },
      { title: "Inserarea implantului", text: "Intervenție chirurgicală rapidă, sigură și fără durere." },
      { title: "Osteointegrarea", text: "Perioada de vindecare în care implantul fuzionează natural cu osul — 3–6 luni." },
      { title: "Montarea coroanei definitive", text: "Fixarea dintelui final care reface frumusețea și masticația." },
    ],
    extraTitle: "Recomandări post-intervenție",
    extraItems: [
      { title: "Igienă riguroasă", text: "Periaj și ață dentară, conform indicațiilor." },
      { title: "Controale periodice", text: "Monitorizarea vindecării și a stabilității." },
      { title: "Renunțarea la obiceiuri nocive", text: "Fumat, alcool, bruxism (acțiunea dinților)." },
    ],
    pricingNote: "Prețuri în EUR, orientative.",
    pricing: [
      { name: "Consultație & plan de tratament", detail: "Evaluare clinică, interpretare CBCT, deviz detaliat", price: "50–100" },
      { name: "Implant dentar (standard / premium)", detail: "Corpul implantului din titan + manoperă chirurgicală", price: "500–850" },
      { name: "Bont protetic", detail: "Element de legătură între implant și coroană", price: "150–300" },
      { name: "Coroană pe implant (zirconiu / ceramică)", detail: "Formă naturală, rezistență și biocompatibilitate", price: "400–800" },
      { name: "Adaos de os / sinus lift", detail: "Proceduri de augmentare osoasă pre-implant", price: "300–1.000" },
    ],
  },
  {
    slug: "chirurgie",
    shortName: "Chirurgie",
    kicker: "Chirurgie dentară",
    title: "Chirurgie Dentară Avansată",
    subtitle: "Intervenții sigure, fără durere și cu o recuperare rapidă.",
    description:
      "Tratamente chirurgicale efectuate cu precizie maximă, tehnologii moderne și protocoale stricte de siguranță. De la extracții complexe și molari de minte, la chirurgie parodontală și reabilitări osoase.",
    heroImage: "/heroes/chirurgie.jpg",
    heroAlt: "Extracție dentară precisă",
    highlights: [
      { title: "Tehnologie modernă", text: "Planificare digitală și echipamente de ultimă oră." },
      { title: "Recuperare rapidă", text: "Protocoale moderne de îngrijire post-operatorie." },
      { title: "Siguranță maximă", text: "Echipă specializată și standarde stricte." },
      { title: "Confort sporit", text: "Anestezie eficientă și monitorizare continuă." },
    ],
    includeTitle: "Ce include chirurgia dentară?",
    includeIntro: "Intervenții esențiale pentru sănătatea și funcționalitatea zâmbetului tău.",
    includes: [
      { title: "Extracții dentare complexe", text: "Include molari de minte incluși sau semi-incluși." },
      { title: "Chirurgie apicală", text: "Rezecții apicale pentru salvarea dinților cu infecții persistente." },
      { title: "Reabilitare osoasă și adaos de os", text: "Pregătirea terenului pentru implanturi." },
      { title: "Sinus lift", text: "Extern și intern, pentru augmentarea osului la maxilarul superior." },
      { title: "Chistectomii", text: "Îndepărtarea formațiunilor benigne." },
    ],
    whyTitle: "De ce să alegi abordarea noastră?",
    whyIntro: "O experiență sigură, confortabilă și predictibilă, pentru fiecare pacient.",
    benefits: [
      { title: "Confort absolut", text: "Tehnici moderne de anestezie și sedare controlată." },
      { title: "Chirurgie minim invazivă", text: "Vindecare rapidă și edem minim." },
      { title: "Echipă supraspecializată", text: "Chirurgie oro-maxilo-facială." },
      { title: "Sterilizare & siguranță", text: "Protocoale stricte de decontaminare." },
      { title: "Monitorizare post-operatorie", text: "Suport permanent și control atent." },
      { title: "Planificare digitală", text: "Predictibilitate totală a rezultatului." },
    ],
    stepsTitle: "Cum decurge intervenția?",
    stepsIntro: "Un proces clar, sigur și bine structurat.",
    steps: [
      { title: "Consultație & imagistică", text: "Evaluare detaliată și tomografie CBCT." },
      { title: "Anestezie & pregătire", text: "Inducerea unui confort total." },
      { title: "Intervenția chirurgicală", text: "Procedură precisă și minim invazivă." },
      { title: "Indicații & recuperare", text: "Recomandări detaliate, control și succedaneu fluid." },
    ],
    extraTitle: "Recomandări post-operatorii",
    extraItems: [
      { title: "Evită efortul fizic", text: "Cel puțin 5–10 zile după intervenție." },
      { title: "Igienă blândă", text: "Periaj delicat și ape de gură recomandate." },
      { title: "Medicație prescrisă", text: "Respectă schema de tratament." },
    ],
    pricing: [
      { name: "Extracție dentară simplă / simplă-rapidă", price: "250–400 lei" },
      { name: "Extracție molar de minte (inclus / semi-inclus)", price: "600–1.200 lei" },
      { name: "Rezecție apicală", price: "800–1.500 lei" },
      { name: "Sinus lift (intern sau extern)", price: "1.500–3.000 lei" },
      { name: "Adaos de os / biomaterial", price: "1.000–2.500 lei" },
    ],
  },
  {
    slug: "estetica",
    shortName: "Estetică",
    kicker: "Estetică dentară · zâmbet · încredere",
    title: "Estetică Dentară Avansată",
    subtitle: "Zâmbetul perfect, natural și plin de încredere pe care îl meriți.",
    description:
      "Transformă-ți zâmbetul cu ajutorul soluțiilor moderne de estetică dentară: fațete ceramice ultra-subțiri, albire profesională de top, coroane estetice din zirconiu și design digital al zâmbetului (Digital Smile Design).",
    heroImage: "/heroes/estetica.jpg",
    heroAlt: "Zâmbet simetric după estetică dentară",
    highlights: [
      { title: "Zâmbet simetric", text: "Proporții armonioase." },
      { title: "Formă perfectă", text: "Contur personalizat." },
      { title: "Culoare naturală", text: "Nuanță potrivită feței." },
    ],
    includeTitle: "Ce include Estetica Dentară?",
    includeIntro: "Soluții complete pentru un zâmbet frumos și sănătos.",
    includes: [
      { title: "Fațete dentare", text: "Ceramică sau compozit pentru corectarea formei, culorii și alinerii dinților." },
      { title: "Albire profesională în cabinet", text: "Sisteme avansate cu lampă pentru rezultate spectaculoase." },
      { title: "Coroane și punți ceramice / zirconiu", text: "Estetică impecabilă și biocompatibilitate maximă." },
      { title: "Design Digital al Zâmbetului", text: "Previzualizarea zâmbetului înainte de începerea tratamentului." },
      { title: "Restaurări fizionomice invizibile", text: "Plombele estetice care imită perfect structura dintelui natural." },
    ],
    whyTitle: "De ce să alegi abordarea noastră?",
    whyIntro: "O experiență premium, centrată pe tine.",
    benefits: [
      { title: "Abordare artistică + precizie digitală", text: "Estetică și tehnologie la cele mai înalte standarde." },
      { title: "Conservarea maximă a țesutului sănătos", text: "Preparare minim-invazivă sau non-invazivă." },
      { title: "Materiale premium de import", text: "Ultra-estetică cu luciu natural." },
      { title: "Previzualizarea rezultatului final", text: "Înainte de șlefuire." },
      { title: "Confort absolut", text: "Proceduri 100% fără durere." },
      { title: "Rezultate spectaculoase", text: "Întinerire fiziognomică reală." },
    ],
    stepsTitle: "Cum se obține un nou zâmbet?",
    stepsIntro: "Un proces clar, sigur și personalizat.",
    steps: [
      { title: "Consultația estetică & DSD", text: "Analiză fiziognomică, fotografii profesionale și simularea zâmbetului." },
      { title: "Pregătirea & amprentarea", text: "Șlefuire minimă-globală și amprentă digitală de înaltă precizie." },
      { title: "Proba provizorie", text: "Testarea formei și esteticii în realitate." },
      { title: "Cimentarea definitivă", text: "Aplicarea fațetelor sau coroanelor finale." },
    ],
    extraTitle: "Sfaturi de întreținere",
    extraItems: [
      { title: "Igienă riguroasă", text: "Periaj, ață dentară și ape de gură." },
      { title: "Evită alimentele care colorează", text: "În primele zile după albire." },
      { title: "Controale periodice", text: "La 6 luni." },
    ],
    pricing: [
      { name: "Albire profesională (cabinet + kit acasă)", price: "400–650 lei" },
      { name: "Fațetă ceramică (e.max) / dinte", price: "1.200–2.000 lei" },
      { name: "Coroană estetică din zirconiu", price: "1.000–1.600 lei" },
      { name: "Digital Smile Design (simulare)", price: "300–400 lei" },
      { name: "Restaurare fizionomică / dinte", price: "600–1.000 lei" },
    ],
  },
  {
    slug: "parodontologie",
    shortName: "Paro",
    kicker: "Parodontologie · sănătatea gingivală",
    title: "Tratamente Parodontale Avansate",
    subtitle: "Salvează-ți zâmbetul tratând afecțiunile gingiilor și ale osului de susținere.",
    description:
      "Gingiile sănătoase sunt fundamentul unui zâmbet stabil. Oferim tratamente moderne, minim invazive, pentru gingivită, parodontită (parodontoză), igienizare profundă subgingivală și regenerare tisulară.",
    heroImage: "/heroes/parodontologie.jpg",
    heroAlt: "Tratament parodontal pe model anatomic",
    highlights: [
      { title: "Diagnostic precis", text: "Măsurători și imagistică." },
      { title: "Tehnologie modernă", text: "Airflow, laser, ultrasonice." },
      { title: "Tratament minim invaziv", text: "Cât mai puțin disconfort." },
      { title: "Rezultate de durată", text: "Mentenanță personalizată." },
    ],
    includeTitle: "Ce tratăm în parodontologie?",
    includeIntro: "Oferim soluții complete pentru sănătatea gingiilor și a osului de susținere.",
    includes: [
      { title: "Gingivita și parodontita", text: "Diagnosticarea precoce și oprirea evoluției bolii." },
      { title: "Detartraj ultrasonic și Airflow profesional", text: "Curățarea depozitelor bacteriene și a tartrului profund." },
      { title: "Chiuretaj în câmp închis / terapie cu laser", text: "Curățarea pungilor parodontale și distrugerea bacteriilor." },
      { title: "Chirurgie parodontală regenerativă", text: "Corectarea retracțiilor gingivale și refacerea osului afectat." },
      { title: "Mentenanță parodontală periodică", text: "Program personalizat de prevenție și monitorizare." },
    ],
    whyTitle: "Semnele că ai nevoie de parodontologie",
    whyIntro: "Nu ignora aceste semnale! Iată indiciile problemelor gingivale și osoase.",
    benefits: [
      { title: "Sângerare gingivală", text: "Aparentă sau în timpul periajului." },
      { title: "Gingii roșii, umflate", text: "Sau sensibilitate la atingere." },
      { title: "Retracție gingivală", text: "Dinții par a fi „mai lungi”." },
      { title: "Respirație urât mirositoare", text: "Cronică (halitoză)." },
      { title: "Mobilitate dentară", text: "Sau modificarea poziției dinților." },
      { title: "Sensibilitate crescută", text: "La cald/rece în zona coletului." },
    ],
    stepsTitle: "Cum decurge tratamentul",
    stepsIntro: "Un proces bine definit, pentru rezultate sigure și de durată.",
    steps: [
      { title: "Evaluarea parodontală", text: "Măsurarea adâncimii pungilor și examinări radiologice." },
      { title: "Igienizarea profesională inițială", text: "Îndepărtarea tartrului supragingival și subgingival." },
      { title: "Terapia specializată", text: "Chiuretaj, terapie cu laser sau intervenții chirurgicale după caz." },
      { title: "Programul de mentenanță", text: "Rechemări periodice la 3–4 luni." },
    ],
    extraTitle: "Sfaturi de igienă pentru gingii sănătoase",
    extraItems: [
      { title: "Duș bucal", text: "Elimină placa bacteriană din zonele greu accesibile." },
      { title: "Ață dentară", text: "Curăță spațiile interdentare." },
      { title: "Periuțe interdentare", text: "Îndepărtează eficient resturile alimentare." },
      { title: "Paste speciale", text: "Cu gel ingrediente active pentru gingii sensibile." },
    ],
    pricing: [
      { name: "Consultație & evaluare parodontală", price: "200–300 lei" },
      { name: "Detartraj, complex + Airflow + Periaj", price: "350–500 lei" },
      { name: "Chiuretaj parodontal / cadran (în câmp închis)", price: "400–600 lei" },
      { name: "Tratament parodontal cu laser (per ședință)", price: "500–800 lei" },
      { name: "Tratament dinți moi (per arcadă)", price: "600–900 lei" },
    ],
  },
  {
    slug: "pedodontie",
    shortName: "Copii",
    kicker: "Pedodonție",
    title: "Pedodonție – Stomatologie pentru Copii",
    subtitle: "Zâmbete sănătoase și fără frica de dentist, construite cu blândețe din copilărie.",
    description:
      "Creăm o atmosferă prietenoasă și relaxantă pentru cei mici. Oferim tratamente stomatologice adaptate vârstei lor, punând un accent deosebit pe prevenție, educație și adaptare psihologică.",
    heroImage: "/heroes/pedodontie.jpg",
    heroAlt: "Consultație stomatologică prietenoasă pentru copii",
    highlights: [
      { title: "Copii fericiți, zâmbete sănătoase!", text: "Atmosferă de joacă, fără teamă." },
    ],
    includeTitle: "Ce include stomatologia pentru copii?",
    includeIntro: "Servicii esențiale pentru un zâmbet sănătos și o dezvoltare armonioasă.",
    includes: [
      { title: "Prima vizită de adaptare", text: "Familiarizarea copilului cu cabinetul, medicul și instrumentele." },
      { title: "Sigilarea dinților temporari și permanenți", text: "Protecție eficientă împotriva cariilor pe șanțuri și fosete." },
      { title: "Tratamentul cariilor la dinții de lapte", text: "Obturații estetice colorate sau albe, materiale sigure." },
      { title: "Tratamentul pulpitei și al urgențelor", text: "Salvarea dinților temporari afectați." },
      { title: "Fluorizare profesională și igienizare", text: "Întărirea smalțului dentar." },
    ],
    whyTitle: "Cum ajutăm copiii să fie relaxați?",
    whyIntro: "Fiecare copil e unic. Noi ne adaptăm nevoilor lui.",
    benefits: [
      { title: "Abordare blândă și răbdătoare", text: "Fără traume sau sperieturi." },
      { title: "Explicații pe limba lor", text: "Tehnica „Spune-Arată-Fă”." },
      { title: "Anestezie topică fără durere", text: "Gel cu arome plăcute înainte de manopere." },
      { title: "Prevenție activă și educație prin joc", text: "Pentru acasă." },
      { title: "Mediu prietenos, colorat și detensionat", text: "Spațiu gândit special pentru copii." },
      { title: "Implicarea părinților", text: "În planul de educație dentară." },
    ],
    stepsTitle: "Etapele primei vizite",
    stepsIntro: "O experiență pozitivă, pas cu pas.",
    steps: [
      { title: "Joaca și acomodarea", text: "Copilul explorează cabinetul, cunoaște medicul și se simte în siguranță." },
      { title: "Consultația prietenoasă", text: "Evaluarea blândă a dințișorilor, fără instrumente înfricoșătoare." },
      { title: "Discuția cu părinții", text: "Prezentarea situației, a igienei și a planului de prevenție." },
      { title: "Mică recompensă & zâmbete", text: "La final, fiecare copil primește o diplomă de curaj și o surpriză." },
    ],
    extraTitle: "Sfaturi pentru părinți",
    extraItems: [
      { title: "Periajul efectuat de părinți", text: "Până la 7–8 ani." },
      { title: "Evitarea sucurilor îndulcite", text: "Și a gustărilor lipicioase." },
      { title: "Vizite la dentist", text: "La fiecare 6 luni." },
    ],
    pricing: [
      { name: "Consultație de aclimatizare / control", price: "150 lei" },
      { name: "Sigilare dinte (temporar sau permanent)", price: "150 lei" },
      { name: "Obturație dinte temporar (plombă color)", price: "200 lei" },
      { name: "Fluorizare (arcadă / ședință scurtă)", price: "120 lei" },
      { name: "Extracție dinte temporar (lapte)", price: "150 lei" },
    ],
  },
  {
    slug: "ortodontie",
    shortName: "Orto",
    kicker: "Ortodonție modernă · zâmbet sănătos · încredere în tine",
    title: "Ortodonție și Aliniere Dentară",
    subtitle: "Zâmbetul armonios și mușcătura corectă la orice vârstă.",
    description:
      "Corectează poziția dinților și a maxilarelor cu ajutorul aparatelor dentare moderne: opțiuni fixe metalice/fizionomice sau gutiere transparente aproape invizibile, adaptate stilului tău de viață.",
    heroImage: "/heroes/ortodontie.jpg",
    heroAlt: "Aparate metalice, fizionomice și alignere transparente",
    highlights: [
      { title: "Rezultate predictibile", text: "Cu tehnologie 3D." },
      { title: "Estetică și confort", text: "La fiecare pas." },
      { title: "O soluție pentru fiecare vârstă", text: "Copii, adolescenți, adulți." },
    ],
    includeTitle: "Ce tipuri de aparate dentare oferim?",
    includeIntro: "Alege-le potrivite pentru nevoile și stilul tău de viață.",
    includes: [
      { title: "Aparate fixe metalice", text: "Clasice, rezistente și extrem de eficiente pentru orice tip de anomalie." },
      { title: "Aparate fixe fizionomice", text: "Din safir sau ceramică, aproape incognito pe dinți." },
      { title: "Aliniatoare transparente", text: "Gutiere tip Spark / Invisalign — soluție detasabilă și estetică." },
      { title: "Aparate ortodontice pentru copii", text: "Dispozitive mobile sau funcționale pentru ghidajul corect al creșterii maxilare." },
    ],
    whyTitle: "De ce să alegi tratamentul ortodontic?",
    whyIntro: "Mai mult decât un zâmbet frumos — un pas spre sănătatea ta pe termen lung.",
    benefits: [
      { title: "Estetică facială îmbunătățită", text: "Și încredere maximă în zâmbet." },
      { title: "Funcționalitate corectă a masticației", text: "Și corectarea ocluziei compact-mandibulare." },
      { title: "Igienă dentară mai ușor de realizat", text: "Dacă dinții sunt aliniați corect." },
      { title: "Prevenirea uzurii premature a smalțului", text: "Și a problemelor parodontale." },
      { title: "Planificare digitală computerizată", text: "Cu vizualizarea rezultatului final." },
      { title: "Monitorizare atentă și ajustări periodice", text: "Comfortabile." },
    ],
    stepsTitle: "Cum decurge tratamentul ortodontic?",
    stepsIntro: "Un proces clar, etapizat și personalizat ortodontic.",
    steps: [
      { title: "Consultația & amprentarea digitală", text: "Analiză ortodontică completă, poze de diagnostic și scanări specifice." },
      { title: "Planul de tratament 3D / Trista", text: "Prezentarea simulării digitale și alegerea tipului de aparat potrivit." },
      { title: "Aplicarea aparatului", text: "Montarea confortabilă a aparatului fix sau livrarea primului set de gutiere." },
      { title: "Controalele periodice & contenția", text: "Vizite la intervale regulate pentru activare, urmate de menținerea rezultatelor." },
    ],
    extraTitle: "Sfaturi de îngrijire esențiale",
    extraItems: [
      { title: "Periaj riguros", text: "După fiecare masă." },
      { title: "Folosirea periutelor interdentare", text: "Și a dușului bucal." },
      { title: "Evitarea alimentelor lipicioase", text: "Sau dure." },
    ],
    pricing: [
      { name: "Consultație ortodontică & plan de tratament", price: "200–400 lei" },
      { name: "Aparat metalic fix metalic (per arcadă)", price: "2.500–3.500 lei" },
      { name: "Aparat dentar fix ceramic / safir (per arcadă)", price: "2.800–4.000 lei" },
      { name: "Aliniatoare transparente (tratament complet)", price: "6.000–12.000 lei" },
      { name: "Set gutiere de contenție (per arcadă)", price: "600–1.000 lei" },
    ],
  },
  {
    slug: "endodontie",
    shortName: "Canal",
    kicker: "Endodonție · precizie · conservare",
    title: "Endodonție la Microscop",
    subtitle: "Salvăm dinții naturali prin tratamente de canal de înaltă precizie.",
    description:
      "Tratamente endodontice moderne efectuate sub microscop optic de înaltă mărire. Eliminăm infecțiile de la rădăcina dintelui fără durere, asigurând conservarea pe termen lung a structurii tale dentare.",
    heroImage: "/heroes/endodontie.jpg",
    heroAlt: "Tratament de canal vizualizat la microscop",
    highlights: [
      { title: "Precizie milimetrică", text: "Vizualizare detaliată a canalelor sub microscop." },
      { title: "Fără durere", text: "Anestezie profundă și proceduri confortabile." },
      { title: "Dinți salvați", text: "Conservăm dinții naturali pe termen lung." },
    ],
    includeTitle: "Ce este tratamentul endodontic?",
    includeIntro: "Un tratament complex, dar necesar, pentru sănătatea dintelui tău.",
    includes: [
      { title: "Ce presupune?", text: "Îndepărtarea pulpei dentare inflamate sau infectate (nervul), curățarea și dezinfectarea riguroasă a canalelor radiculare și sigilarea lor tridimensională." },
      { title: "Când este necesar?", text: "În caz de carii profunde, traumatisme, fracturi dentare sau infecții vechi (abcese/granulome)." },
      { title: "Rolul microscopului", text: "Permite detectarea detaliilor anatomice ascunse: canale suplimentare sau a instrumentelor fracturate, oferind o rată de succes maximă." },
    ],
    whyTitle: "De ce să alegi abordarea noastră?",
    whyIntro: "Tehnologie avansată. Experiență. Grijă pentru tine.",
    benefits: [
      { title: "Vizibilitate maximă și precizie milimetrică", text: "Datorită microscopului operator." },
      { title: "Confort absolut și fără durere", text: "Efectuate sub anestezie profundă." },
      { title: "Salvarea dinților", text: "Care altfel ar trebui extrași." },
      { title: "Sisteme rotative moderne și digă", text: "Pentru sterilizare perfectă." },
      { title: "Mai puține ședințe", text: "Și disconfort post-operator redus." },
      { title: "Experiență în cazuri complexe", text: "Retratamente endodontice." },
    ],
    stepsTitle: "Cum decurge un tratament de canal?",
    stepsIntro: "4 pași clari pentru un rezultat sigur și durabil.",
    steps: [
      { title: "Diagnostic & izolare", text: "Evaluare clinică, radiografie digitală și aplicarea digei dentare pentru izolare totală." },
      { title: "Accesul & curățarea sub microscop", text: "Localizarea canalelor, îndepărtarea țesutului infectat și dezinfecție chimică." },
      { title: "Obturația tridimensională", text: "Sigilarea ermetică a sistemului canalelor cu materiale biocompatibile." },
      { title: "Restaurarea finală", text: "Refacerea coronară a dintelui prin plombă estetică sau coroană de protecție." },
    ],
    extraTitle: "Recomandări importante",
    extraItems: [
      { title: "Evită masticarea pe dintele tratat", text: "Temporar până la restaurarea finală." },
      { title: "Este posibilă o sensibilitate coronară", text: "Și trecătoare în primele zile post-tratament." },
    ],
    pricing: [
      { name: "Consultație endodontică & diagnostic", price: "200–300 lei" },
      { name: "Tratament de canal – Monoradicular (1 canal)", price: "600–900 lei" },
      { name: "Tratament de canal – Pluriradicular (2–3 canale)", price: "900–1.400 lei" },
      { name: "Retratament endodontic la microscop", price: "1.300–1.800 lei" },
      { name: "Aplicare splint din fibră de sticlă", price: "400–700 lei" },
    ],
  },
  {
    slug: "radiologie",
    shortName: "3D / RX",
    kicker: "Radiologie dentară & imagistică 3D",
    title: "Radiologie Dentară Digitală",
    subtitle: "Imagistică de înaltă precizie și iradiere minimă pentru un diagnostic corect.",
    description:
      "Beneficiază de tehnologie radiologică de ultimă generație. Oferim pe loc, rapid și în deplină siguranță: radiografii panoramice, retroalveolare și tomografii computerizate 3D (CBCT) esențiale pentru planurile de tratament.",
    heroImage: "/heroes/radiologie.jpg",
    heroAlt: "Aparat CBCT și imagini radiologice 3D",
    highlights: [
      { title: "CBCT 3D", text: "Planificare precisă." },
      { title: "Panoramic", text: "Vedere de ansamblu." },
      { title: "Doze mici", text: "Protocoale digitale." },
    ],
    includeTitle: "Ce tipuri de investigații oferim?",
    includes: [
      { title: "Tomografie computerizată 3D (CBCT)", text: "Esențială pentru implantologie, chirurgie și endodonție avansată." },
      { title: "Radiografie panoramică (ortopantomogramă)", text: "Imagine de ansamblu a întregului arcadă dentară și a structurilor adiacente." },
      { title: "Radiografie retroalveolară (dentala localizată)", text: "Detalii milimetrice pentru un singur dinte sau un grup restrâns." },
      { title: "Radiografie de bitewing", text: "Pentru detectarea timpurie a cariilor ocluzive în dinții dinți." },
      { title: "Teleradiografie (profil/frontală)", text: "Indispensabilă pentru planificarea tratamentelor ortodontice." },
    ],
    whyTitle: "De ce să alegi serviciul nostru de radiologie?",
    benefits: [
      { title: "Doza de iradiere redusă", text: "Tehnologii senzorilor digitali ultramoderni." },
      { title: "Rezultate instantanee", text: "Lămuri pe loc, digitale, pe e-mail sau pe suport dedicat." },
      { title: "Claritate și precizie", text: "Chiar și în imagistică 3D." },
      { title: "Confort absolut", text: "Investigații rapide, fără timp de așteptare." },
      { title: "Echipamente calibrate", text: "Diagnostic conform normelor stricte de protecție radiologică." },
      { title: "Totul într-un singur loc", text: "Posibilitatea realizării tuturor investigațiilor cu tratamentul." },
    ],
    stepsTitle: "Cum se desfășoară o investigație?",
    steps: [
      { title: "Prezentarea în cabinet", text: "Personalul nostru medical îți va explica procedura investigației." },
      { title: "Poziționarea rapidă și sigură", text: "Te poziționăm confortabil, conform necesităților zonei de interes, ținând cont de protecția de plumb." },
      { title: "Livrarea rezultatelor", text: "Primești investigația procesată instant. Pe e-mail, digital, pe suport printat." },
    ],
    extraTitle: "Recomandări importante",
    extraItems: [
      { title: "Anunță medicul în caz de sarcină", text: "Pentru siguranța ta și a copilului tău." },
      { title: "Îndepărtează obiectele metalice", text: "Din zona capului (ochelari, cercei, piercing-uri etc.)." },
    ],
    pricing: [
      { name: "Radiografie retroalveolară (dentală)", price: "60 lei" },
      { name: "Radiografie panoramică (ortopantomogramă)", price: "150 lei" },
      { name: "Tomografie 3D CBCT 1 os / segment (1/4 maxilar)", price: "250 lei" },
      { name: "Teleradiografie de profil", price: "200 lei" },
      { name: "Set diagnostic (panoramică + CBCT parțial)", price: "350 lei" },
    ],
  },
];

export function getService(slug: string) {
  return services.find((s) => s.slug === slug);
}
